source 'https://rubygems.org'
ruby "2.4.1"

gem "jekyll"
gem "rack-jekyll"
gem "kramdown"
gem "puma"

# Gems to generate RailsGuides HTML from MD
gem "rack-cache", "~> 1.2"
gem "rake"
gem "activesupport"
gem "actionpack"
gem "nokogiri"
gem "redcarpet"

# Monitoring tools
gem "newrelic_rpm"

# Need latest json for using Ruby 2.4.0
gem "json", "~> 2.0"

# SSL in Production
gem "acme_challenge"
gem "rack-rewrite", "~> 1.5.0"
# FIXME: Remove this fork after https://github.com/rack/rack-contrib/pull/129 is merged.
gem "rack-contrib", github: "bigcartel/rack-contrib", branch: "master"

# Testing links by hand
gem "html-proofer"

group :development do
  # Generate docset
  gem "docset"
  gem "gtt-downloader"
end

group :development, :test do
  gem "rb-readline"
  gem "pry-byebug"
end

group :test do
  gem "capybara"
  gem "rspec"
  gem "turnip"
  gem "wraith"
end
